export let data = [
  {
    id: 1,
    name: "Avail 1",
    sunday: [],
    monday: [],
    tuesday: [],
    wednesday: [],
    thursday: [],
    friday: [],
    saturday: [],
    isDefault: true,
    timezone: "Asia/Kolkata +5:30 GMT",
  },
  {
    id: 2,
    name: "Avail 2",
    sunday: [],
    monday: [],
    tuesday: [],
    wednesday: [],
    thursday: [],
    friday: [],
    saturday: [],
    isDefault: false,
    timezone: "Asia/Kolkata +5:30 GMT",
  },
  {
    id: 3,
    name: "Avail 3",
    sunday: [],
    monday: [],
    tuesday: [],
    wednesday: [],
    thursday: [],
    friday: [],
    saturday: [],
    isDefault: false,
    timezone: "Asia/Kolkata +5:30 GMT",
  },
];
